import Head from 'next/head';
import Keyboard from '@/components/Keyboard';
import Grid from '@/components/Grid';
import { useEffect, useState } from 'react';
import { useWordle } from '@/utils/WordleHook';
import { getRandomSolution } from '@/utils/targetWords';

export default function Home() {
    const [solution, setSolution] = useState('');
    const { addWordleListener, removeWordleListener, guesses, currentGuess } =
        useWordle(solution);

    useEffect(() => {
        const randSolution = getRandomSolution();
        setSolution(randSolution);
    }, [setSolution]);

    useEffect(() => {
        addWordleListener();
        return () => {
            removeWordleListener();
        };
    }, [addWordleListener, removeWordleListener]);
    return (
        <>
            <Head>
                <title>Wordle Unlimited</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="flex justify-center items-center text-[1.5em] font-extrabold tracking-tight mt-[-0.5em] p-4 text-white border-b border-gray-500 border-opacity-25 header">
                    Wordle Unlimited
                </h1>
                <div data-alert-container className="alert-container"></div>
                <Grid guesses={guesses} currentGuess={currentGuess} />
                <Keyboard />
            </main>
        </>
    );
}
